language: julia
sudo: false
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
        - julia: nightly
notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("MatrixDepot")'
  - julia -e ' Pkg.test("MatrixDepot"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("MatrixDepot")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
